application: ride-agg
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:

- url: /static
  static_dir: static

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
